version: '3.9'

services:
  app:
    build:
      args:
          user: 1000
          uid: 1000
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: network-app
    restart: unless-stopped
    working_dir: /var/www/
    tty: true
    volumes:
      - ./:/var/www
    networks:
      - web

  web:
    container_name: network-web
    image: nginx:1.25.3-alpine
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    tty: true
    ports:
      - "1010:80"
    restart: unless-stopped
    networks:
      - web 

  db:
    image: mysql:8.1.0
    container_name: network-db
    restart: always
    environment:
      - MYSQL_DB=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - web 

  phpmyadmin:
      image: phpmyadmin:latest
      container_name: network-phpmyadmin
      restart: always
      links:
        - db
      ports:
        - 8080:80
      environment:
        - PMA_HOST=db
        - PMA_USER=root
        - PMA_PASSWORD=password
      networks:
        - web 

networks:
  web:
    driver: bridge
